### ISSUE TITLE
Reaction blueprints issues

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#130]
1. Reaction blueprints can have their ME changed in EVEIPH. If you have default ME/TE set this will set the reaction blueprints to have this ME.

![image](https://user-images.githubusercontent.com/8939440/47266299-f2b30880-d566-11e8-95af-c6075b857d0d.png)
example

However, in-game, reactions cannot be researched leading to incorrect calculations of qty/volume/cost etc.

2. Reactions are using manufacturing drop down ME instead of reactions drop down ME. Has structures that do not allow reactions in them.
![image](https://user-images.githubusercontent.com/8939440/47266084-23457300-d564-11e8-8068-60db5d16f6ef.png)
Note qty 99 instead of 98 expected for 2.64% ME bonus.

![image](https://user-images.githubusercontent.com/8939440/47266088-2ccedb00-d564-11e8-856c-3d2c8f6273ae.png)

Manufacturing bonus as 1% (unrigged eng complex)

**Comment by Zifrian** [comment]
This should be fixed now in Build 4.0.6895.17505.

**Comment by zductiv** [comment]
Still seeing part 2 as an issue.

Take antimatter reactor unit blueprint production as an example.

The drop down activities when built T2 with processed moon materials selected are:
Manufacturing
Component Manufacturing.

I would expect to see: 
Manufacturing
Reactions

intermediate reaction to composite -> composite manufacture to t2 comp.

When build T2/T3 with raw moon/gas materials is selected I see:
Manufacturing
Component Manufacturing

I'd expect to see:
Manufacturing
Reactions

raw moon reaction to intermediate -> intermediate reaction to composite -> composite manufacture to t2 comp.

With build t2/t3 with adv. moon gas/materials selected you see: 
Manufacturing
Component Manufacturing

I'd expect to see: 
Manufacturing

as only composite->t2 components step.
